Added struct for SEXS AVR
NREL-SIIP/PowerSystems.jl pull request #734
Opened 2021-05-06 19:27 UTC by m-bossart

2021-05-06 22:19 UTC, jd-lara requested changes
Please also add the export of SEXS in the file `PowerSystems.jl`

2021-05-06 22:19 UTC, jd-lara commented on src/descriptors/power_system_structs.json
> +          "comment": "The states are:\n\tVf: Voltage field,\n\tVr: Lead-lag state",
can you remove the break lines `\n`

2021-05-07 19:12 UTC, jd-lara commented
@m-bossart more testing is missing to merge the PR: 

see  https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base

2021-05-07 19:43 UTC, m-bossart commented
Can you elaborate on this? Is this a test that I need to implement or that happens automatically? From what I can tell there is no method defined to add the new component to the system, but I'm not sure exactly what I need to do.

2021-05-10 18:46 UTC, merged